---
- name: deploy certificates
  copy:
    src: "{{ certbot_cert_path }}"
    dest: "/etc/ssl/certs/{{ certbot_cert_name }}.pem"
    mode: 0644
  notify:
    - reload nginx

- name: deploy private key
  copy:
    src: "{{ certbot_key_path }}"
    dest: "/etc/ssl/private/{{ certbot_cert_name }}.key"
    mode: 0640
  notify:
    - reload nginx

- name: backup certs
  include_role:
    name: certbot_common
    tasks_from: backup
  delegate_to: localhost
