---
- name: generate via webroot
  shell: >
    certbot certonly
    --non-interactive 
    --webroot
    --webroot-path "{{ certbot_webroot_path }}"
    --cert-name "{{ certbot_cert_name }}"
    --domains "{{ certbot_domains|join(",") }}"

- name: fix permissions
  include_role:
    name: certbot_common
    tasks_from: permissions
