---
- name: add certbot ppa
  apt_repository:
    repo: "{{ certbot_repo }}"

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nginx
    - certbot

- name: registration details
  shell: >
    certbot register
    --agree-tos
    --update-registration
    --email {{ certbot_email }}
    --no-eff-email

- name: renew hook script
  template:
    src: certbot-renew-hook.j2
    dest: "{{ certbot_renew_hook_path }}"
    mode: 0775

- name: service override dir
  file:
    path: /etc/systemd/system/certbot.service.d
    state: directory

- name: service override
  template:
    src: certbot-renew-service-override.j2
    dest: /etc/systemd/system/certbot.service.d/override.conf
    mode: 0644
  notify: reload certbot

- name: stat cert
  stat:
    path: "{{ certbot_cert_path }}"
  register: cert

- include: certonly.yml
  when: not cert.stat.exists and certbot_generate

- include: renew.yml
  when: cert.stat.exists and certbot_renew
