---
- name: renew via webroot
  shell: >
    certbot renew
    --non-interactive 
    --webroot
    --webroot-path={{ certbot_webroot_path }}
    --cert-name "{{ certbot_cert_name }}"

- name: fix permissions
  include_role:
    name: certbot_common
    tasks_from: permissions
